[workspace]
members = [
    "src/amb-rs",
    "src/amb-rs-lib",
    "src/amb-rs-tests",
    "src/ManagerLauncher",
    "src/ManagerLauncher_link",
    "src/Sonic4ModManager",
    "src/Sonic4ModManager_link",
    "src/Sonic4FilePatcher",
    "src/OneClickModInstaller"
]
resolver = "3"